language: node_js
before_install: npm install -g yarn bower
install: yarn && bower install
script: npm run build && npm test
before_cache: npm prune
branches:
  only:
    - master
sudo: false
cache:
  directories:
    - node_modules
    - bower_modules
    - output
